// <auto-generated />
using System;
using Hipos.Api.Features;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hipos.Api.Features.Migrations
{
    [DbContext(typeof(FeatureDbContext))]
    partial class FeatureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("modules")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hipos.Api.Features.BranchFeatureRow", b =>
                {
                    b.Property<string>("FirmId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("firm_id");

                    b.Property<string>("BranchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("branch_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("feature_key");

                    b.Property<bool>("DesiredEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("desired_enabled");

                    b.Property<bool>("EffectiveForNewWork")
                        .HasColumnType("boolean")
                        .HasColumnName("effective_for_new_work");

                    b.Property<int>("InFlightWorkCount")
                        .HasColumnType("integer")
                        .HasColumnName("in_flight_work_count");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("FirmId", "BranchId", "Key");

                    b.ToTable("branch_feature_states", "modules", t =>
                        {
                            t.HasCheckConstraint("ck_feature_version_positive", "version > 0");

                            t.HasCheckConstraint("ck_in_flight_nonnegative", "in_flight_work_count >= 0");
                        });
                });

            modelBuilder.Entity("Hipos.Api.Features.FeatureAuditRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("branch_id");

                    b.Property<bool>("DesiredEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("desired_enabled");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("feature_key");

                    b.Property<string>("FirmId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("firm_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "BranchId", "Id");

                    b.ToTable("feature_audit", "modules");
                });
#pragma warning restore 612, 618
        }
    }
}
