// <auto-generated />
using System;
using Hipos.Api.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hipos.Api.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261006110237_InitCatalog")]
    partial class InitCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hipos.Api.Catalog.CatalogBranchPriceRow", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("BranchId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("branch_id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.HasKey("ProductId", "BranchId");

                    b.ToTable("branch_prices", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_branch_price_nonnegative", "amount_minor >= 0");
                        });
                });

            modelBuilder.Entity("Hipos.Api.Catalog.CatalogProductRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Allergens")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergens");

                    b.Property<long>("BasePriceMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("base_price_minor");

                    b.PrimitiveCollection<string[]>("BranchIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("branch_ids");

                    b.Property<string>("BrandId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("brand_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("category_name");

                    b.PrimitiveCollection<string[]>("Channels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("channels");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("FirmId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("firm_id");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("OptionGroups")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("option_groups");

                    b.Property<bool>("RecipeLinked")
                        .HasColumnType("boolean")
                        .HasColumnName("recipe_linked");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FirmId", "CategoryId");

                    b.HasIndex("FirmId", "Sku")
                        .IsUnique();

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_base_price_nonnegative", "base_price_minor >= 0");

                            t.HasCheckConstraint("ck_product_status", "status IN ('draft', 'published')");

                            t.HasCheckConstraint("ck_product_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("Hipos.Api.Catalog.CatalogBranchPriceRow", b =>
                {
                    b.HasOne("Hipos.Api.Catalog.CatalogProductRow", "Product")
                        .WithMany("BranchPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hipos.Api.Catalog.CatalogProductRow", b =>
                {
                    b.Navigation("BranchPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
